Makes the script compatible with `sh`
Updates the shebang and script to allow it to be ran by `sh`.
This increases the compatibility of the script.

diff --git a/vim-awesome b/vim-awesome
--- a/vim-awesome
+++ b/vim-awesome
@@ -1,4 +1,4 @@
-#!/usr/bin/bash
+#!/bin/sh
 
 # URLs
 BASE_URL='https://vimawesome.com'
@@ -24,10 +24,9 @@ test -d "$VA_CACHE_DIR" || mkdir -p "$VA_CACHE_DIR" || exit 1
 test -d "$VA_PLUGINS_DATA_DIR" || mkdir -p "$VA_PLUGINS_DATA_DIR" || exit 1
 
 getPluginData() {
-	local jsonFile
 	jsonFile="$VA_PLUGINS_DATA_DIR/$1.json"
 
-	if [[ -f "$jsonFile" ]]; then
+	if [ -f "$jsonFile" ]; then
 		cat "$jsonFile"
 	else
 		curl -s "$PLUGINS_URL/$1" | tee "$jsonFile"
@@ -36,7 +35,6 @@ getPluginData() {
 
 prettyFmtJsonPluginData() {
 	# Read the json data from the input
-	local data name author category description;
 	read -r data;
 
 	name=$(echo "$data" | jq -r ".$JSON_NAME");
@@ -56,66 +54,62 @@ va_clear() {
 }
 
 va_search() {
-	TEMP=$(getopt -o 'ci' -l 'cached,installed' -n 'vim-awesome' -- "$@")
-	if [ $? -ne 0 ]; then
+	if TEMP=$(getopt -o 'ci' -l 'cached,installed' -n 'vim-awesome' -- "$@"); then
+
+		eval set -- "$TEMP"
+
+		# Parse option flags
+		while true; do
+			case "$1" in
+				'-c'|'--cached')
+					onlyCached=1
+					shift
+				;;
+				'-i'|'--installed')
+					onlyInstalled=1
+					shift
+				;;
+				'--')
+					shift
+					break
+				;;
+				*)
+					echo 'CLI parse error' >&2
+				;;
+			esac	
+		done
+
+		if [ "$onlyCached" -eq 1 ]; then
+			find "$VA_PLUGINS_DATA_DIR" -mindepth 1 -maxdepth 1 -type f -printf '%f\n' | sed 's/.json$//'
+			exit 0
+		fi
+
+		if [ "$onlyInstalled" -eq 1 ]; then
+			test -d "$VA_VIM_PLUGIN_DIR" && find "$VA_VIM_PLUGIN_DIR" -mindepth 1 -maxdepth 1 -type d -printf '%f\n'
+			exit 0
+		fi
+
+		# Performs the search
+		jsonData=$(curl -s "$PLUGINS_URL?query=$1&page=1" | jq -c -r '.plugins[]')
+		echo "$jsonData" | while read -r plugin; do
+			pluginName=$(echo "$plugin" | jq -r ".$JSON_NAME")
+
+			# Cache the plugin information
+			echo "$plugin" > "$VA_PLUGINS_DATA_DIR/$pluginName.json"
+
+			# Display the plugin information
+			echo "$plugin" | jq -r ".$JSON_NAME"
+			echo "$plugin" | jq -r ".$JSON_DESCRIPTION" | fold -s | sed 's/^/\t/'
+		done
+	else
 		exit 1
 	fi
-
-	eval set -- "$TEMP"
-
-	# Parse option flags
-	local onlyInstalled
-	while true; do
-		case "$1" in
-			'-c'|'--cached')
-				onlyCached=1
-				shift
-			;;
-			'-i'|'--installed')
-				onlyInstalled=1
-				shift
-			;;
-			'--')
-				shift
-				break
-			;;
-			*)
-				echo 'CLI parse error' >&2
-			;;
-		esac	
-	done
-
-	if [[ "$onlyCached" -eq 1 ]]; then
-		find "$VA_PLUGINS_DATA_DIR" -mindepth 1 -maxdepth 1 -type f -printf '%f\n' | sed 's/.json$//'
-		exit 0
-	fi
-
-	if [[ "$onlyInstalled" -eq 1 ]]; then
-		test -d "$VA_VIM_PLUGIN_DIR" && find "$VA_VIM_PLUGIN_DIR" -mindepth 1 -maxdepth 1 -type d -printf '%f\n'
-		exit 0
-	fi
-
-	# Performs the search
-	local jsonData pluginName
-	jsonData=$(curl -s "$PLUGINS_URL?query=$1&page=1" | jq -c -r '.plugins[]')
-	while read -r plugin; do
-		pluginName=$(echo "$plugin" | jq -r ".$JSON_NAME")
-
-		# Cache the plugin information
-		echo "$plugin" > "$VA_PLUGINS_DATA_DIR/$pluginName.json"
-
-		# Display the plugin information
-		local name description
-		echo "$(echo "$plugin" | jq -r ".$JSON_NAME")"
-		echo "$(echo "$plugin" | jq -r ".$JSON_DESCRIPTION" | fold -s | sed 's/^/\t/')"
-	done <<< "$jsonData"
 }
 
 va_show() {
 	TEMP=$(getopt -o 'w' -l 'web' -n 'vim-awesome' -- "$@" || exit 1)
 	eval set -- "$TEMP"
 
-	local showWeb;
 	while true; do
 		case "$1" in
 			'-w'|'--web')
@@ -129,13 +123,12 @@ va_show() {
 		esac
 	done
 
-	local isXdgOpenInstalled;
-	isXdgOpenInstalled=$(type -t xdg-open)
-	if [[ "$showWeb" -eq 1 && -n "$isXdgOpenInstalled" ]]; then
+	isXdgOpenInstalled=$(which xdg-open 2> /dev/null)
+	if [ "$showWeb" -eq 1 ] && [ -n "$isXdgOpenInstalled" ]; then
 		xdg-open "$BASE_URL/plugin/$1"
 	else
 		# Alert the user if the website was requested, but couldn't be launched
-		if [[ "$showWeb" -eq 1 ]]; then
+		if [ "$showWeb" -eq 1 ]; then
 			echo "ERROR: The '--web' flag was used, but xdg-open is not installed" > /dev/stderr
 		fi
 
@@ -144,7 +137,6 @@ va_show() {
 }
 
 va_install() {
-	local jsonData pluginName repoUrl
 
 	# Get the plugin data
 	jsonData=$(getPluginData "$1" | jq -r '{ github_url, slug }')
@@ -163,12 +155,29 @@ va_uninstall() {
 	rm -rf "${VA_VIM_PLUGIN_DIR:?}/$1"
 }
 
-functionName="va_$1"
-
-if [[ $(type -t "$functionName") == 'function' ]]; then
-	shift
-	eval "$functionName ${*:1}"
-else
-	echo "The command '$1' is not recognized" > /dev/stderr
-fi
+va_command="$1"
+shift
+case "$va_command" in
+	'clear')
+		va_clear "$@"
+		;;
+	'search')
+		va_search "$@"
+		;;
+	'show')
+		va_show "$@"
+		;;
+	'install')
+		va_install "$@"
+		;;
+	'upgrade')
+		va_upgrade "$@"
+		;;
+	'uninstall')
+		va_uninstall "$@"
+		;;
+	*)
+		echo "The command '$1' is not recognized" > /dev/stderr
+		;;
+esac
 
